[
  {
    "name": "Solicitação",
    "id": "22224673",
    "type": "application/pdf",
    "length": 931032,
    "originalFileName": "SD_240715_141024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224673/download",
    "displayName": "Solicitação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovante de pagamento",
    "id": "22224679",
    "type": "application/pdf",
    "length": 445021,
    "originalFileName": "Boleto e Comprovante de pagamento.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224679/download",
    "displayName": "Comprovante de pagamento",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Procuração",
    "id": "22224685",
    "type": "application/pdf",
    "length": 170062,
    "originalFileName": "Procuração_240715_141053.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224685/download",
    "displayName": "Procuração",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Cópias simples do RG e do CPF ou da CNH",
    "id": "22224688",
    "type": "application/pdf",
    "length": 107014,
    "originalFileName": "RG CPF RAFAEL.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224688/download",
    "displayName": "Cópias simples do RG e do CPF ou da CNH",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documento que comprove a propriedade do imóvel.",
    "id": "22224743",
    "type": "application/pdf",
    "length": 973344,
    "originalFileName": "Contrato social AUGE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224743/download",
    "displayName": "Documento que comprove a propriedade do imóvel.",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovação de área do terreno",
    "id": "22224745",
    "type": "application/pdf",
    "length": 45434,
    "originalFileName": "iptu2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224745/download",
    "displayName": "Comprovação de área do terreno",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Mapa de acesso ao local.",
    "id": "22224702",
    "type": "application/pdf",
    "length": 229681,
    "originalFileName": "Mapa de Acesso.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224702/download",
    "displayName": "Mapa de acesso ao local.",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "MCE adicional de Renovação de Licença de Operação",
    "id": "22224712",
    "type": "application/pdf",
    "length": 293452,
    "originalFileName": "MCE Adicional_240715_141145.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224712/download",
    "displayName": "MCE adicional de Renovação de Licença de Operação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Certificado de Regularidade do Cadastro Técnico Federal",
    "id": "22224718",
    "type": "application/pdf",
    "length": 21203,
    "originalFileName": "Ibama Certificado Regularidade val 15.10.2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224718/download",
    "displayName": "Certificado de Regularidade do Cadastro Técnico Federal",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documentação específica para licenciamento de Postos",
    "id": "22224719",
    "type": "application/pdf",
    "length": 7951511,
    "originalFileName": "ESTANQUEIDADE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224719/download",
    "displayName": "Documentação específica para licenciamento de Postos",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Manifestação do órgão responsável pelo sistema público de esgotos",
    "id": "22224722",
    "type": "application/pdf",
    "length": 295948,
    "originalFileName": "Conta de agua AUGE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224722/download",
    "displayName": "Manifestação do órgão responsável pelo sistema público de esgotos",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "MCE - Adicional de postos - renovação",
    "id": "22224729",
    "type": "application/pdf",
    "length": 412904,
    "originalFileName": "MCE Renovação_240715_141115.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224729/download",
    "displayName": "MCE - Adicional de postos - renovação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Outros Documentos.pdf",
    "id": "22224746",
    "type": "application/pdf",
    "length": 747988,
    "originalFileName": "CLCB.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224746/download",
    "displayName": "Outros Documentos.pdf",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Outros Documentos.pdf",
    "id": "22224753",
    "type": "application/pdf",
    "length": 100634,
    "originalFileName": "CNPJ Auge2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224753/download",
    "displayName": "Outros Documentos.pdf",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Outros Documentos.pdf",
    "id": "22224759",
    "type": "application/pdf",
    "length": 868823,
    "originalFileName": "Procuração Rafael.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224759/download",
    "displayName": "Outros Documentos.pdf",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Outros Documentos.pdf",
    "id": "22224763",
    "type": "application/pdf",
    "length": 85432,
    "originalFileName": "RG-CPF Edson.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224763/download",
    "displayName": "Outros Documentos.pdf",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Solicitação",
    "id": "22224673",
    "type": "application/pdf",
    "length": 931032,
    "originalFileName": "SD_240715_141024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224673/download",
    "displayName": "Solicitação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovante de pagamento",
    "id": "22224679",
    "type": "application/pdf",
    "length": 445021,
    "originalFileName": "Boleto e Comprovante de pagamento.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224679/download",
    "displayName": "Comprovante de pagamento",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Procuração",
    "id": "22224685",
    "type": "application/pdf",
    "length": 170062,
    "originalFileName": "Procuração_240715_141053.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224685/download",
    "displayName": "Procuração",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Cópias simples do RG e do CPF ou da CNH",
    "id": "22224688",
    "type": "application/pdf",
    "length": 107014,
    "originalFileName": "RG CPF RAFAEL.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224688/download",
    "displayName": "Cópias simples do RG e do CPF ou da CNH",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documento que comprove a propriedade do imóvel.",
    "id": "22224743",
    "type": "application/pdf",
    "length": 973344,
    "originalFileName": "Contrato social AUGE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224743/download",
    "displayName": "Documento que comprove a propriedade do imóvel.",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovação de área do terreno",
    "id": "22224745",
    "type": "application/pdf",
    "length": 45434,
    "originalFileName": "iptu2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224745/download",
    "displayName": "Comprovação de área do terreno",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Mapa de acesso ao local.",
    "id": "22224702",
    "type": "application/pdf",
    "length": 229681,
    "originalFileName": "Mapa de Acesso.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224702/download",
    "displayName": "Mapa de acesso ao local.",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "MCE adicional de Renovação de Licença de Operação",
    "id": "22224712",
    "type": "application/pdf",
    "length": 293452,
    "originalFileName": "MCE Adicional_240715_141145.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224712/download",
    "displayName": "MCE adicional de Renovação de Licença de Operação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Certificado de Regularidade do Cadastro Técnico Federal",
    "id": "22224718",
    "type": "application/pdf",
    "length": 21203,
    "originalFileName": "Ibama Certificado Regularidade val 15.10.2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224718/download",
    "displayName": "Certificado de Regularidade do Cadastro Técnico Federal",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documentação específica para licenciamento de Postos",
    "id": "22224719",
    "type": "application/pdf",
    "length": 7951511,
    "originalFileName": "ESTANQUEIDADE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224719/download",
    "displayName": "Documentação específica para licenciamento de Postos",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Manifestação do órgão responsável pelo sistema público de esgotos",
    "id": "22224722",
    "type": "application/pdf",
    "length": 295948,
    "originalFileName": "Conta de agua AUGE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224722/download",
    "displayName": "Manifestação do órgão responsável pelo sistema público de esgotos",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "MCE - Adicional de postos - renovação",
    "id": "22224729",
    "type": "application/pdf",
    "length": 412904,
    "originalFileName": "MCE Renovação_240715_141115.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224729/download",
    "displayName": "MCE - Adicional de postos - renovação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Solicitação",
    "id": "22224673",
    "type": "application/pdf",
    "length": 931032,
    "originalFileName": "SD_240715_141024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224673/download",
    "displayName": "Solicitação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovante de pagamento",
    "id": "22224679",
    "type": "application/pdf",
    "length": 445021,
    "originalFileName": "Boleto e Comprovante de pagamento.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224679/download",
    "displayName": "Comprovante de pagamento",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Procuração",
    "id": "22224685",
    "type": "application/pdf",
    "length": 170062,
    "originalFileName": "Procuração_240715_141053.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224685/download",
    "displayName": "Procuração",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Cópias simples do RG e do CPF ou da CNH",
    "id": "22312444",
    "type": "application/pdf",
    "length": 100634,
    "originalFileName": "CNPJ Auge2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312444/download",
    "displayName": "Cópias simples do RG e do CPF ou da CNH",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Ficha cadastral simplificada emitida pelo site da JUCESP",
    "id": "22312455",
    "type": "application/pdf",
    "length": 131867,
    "originalFileName": "ficha simplificada JUCESP.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312455/download",
    "displayName": "Ficha cadastral simplificada emitida pelo site da JUCESP",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documentação ME-EPP-MEI",
    "id": "22312486",
    "type": "application/pdf",
    "length": 644100,
    "originalFileName": "Declaração EPP.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312486/download",
    "displayName": "Documentação ME-EPP-MEI",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documento que comprove a propriedade do imóvel.",
    "id": "22224743",
    "type": "application/pdf",
    "length": 973344,
    "originalFileName": "Contrato social AUGE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224743/download",
    "displayName": "Documento que comprove a propriedade do imóvel.",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovação de área do terreno",
    "id": "22312479",
    "type": "application/pdf",
    "length": 1019405,
    "originalFileName": "Matricula AUGE Atualizada.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312479/download",
    "displayName": "Comprovação de área do terreno",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Mapa de acesso ao local.",
    "id": "22224702",
    "type": "application/pdf",
    "length": 229681,
    "originalFileName": "Mapa de Acesso.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224702/download",
    "displayName": "Mapa de acesso ao local.",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "MCE adicional de Renovação de Licença de Operação",
    "id": "22224712",
    "type": "application/pdf",
    "length": 293452,
    "originalFileName": "MCE Adicional_240715_141145.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224712/download",
    "displayName": "MCE adicional de Renovação de Licença de Operação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovação da solicitação",
    "id": "22312553",
    "type": "application/pdf",
    "length": 21203,
    "originalFileName": "Ibama Certificado Regularidade val 15.10.2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312553/download",
    "displayName": "Comprovação da solicitação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Certificado de Regularidade do Cadastro Técnico Federal",
    "id": "22224718",
    "type": "application/pdf",
    "length": 21203,
    "originalFileName": "Ibama Certificado Regularidade val 15.10.2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224718/download",
    "displayName": "Certificado de Regularidade do Cadastro Técnico Federal",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documentação específica para licenciamento de Postos",
    "id": "22224719",
    "type": "application/pdf",
    "length": 7951511,
    "originalFileName": "ESTANQUEIDADE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224719/download",
    "displayName": "Documentação específica para licenciamento de Postos",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Manifestação do órgão responsável pelo sistema público de esgotos",
    "id": "22224722",
    "type": "application/pdf",
    "length": 295948,
    "originalFileName": "Conta de agua AUGE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224722/download",
    "displayName": "Manifestação do órgão responsável pelo sistema público de esgotos",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "MCE - Adicional de postos - renovação",
    "id": "22224729",
    "type": "application/pdf",
    "length": 412904,
    "originalFileName": "MCE Renovação_240715_141115.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224729/download",
    "displayName": "MCE - Adicional de postos - renovação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovação de cumprimento de exigências (novo texto 15-03-16)",
    "id": "22312529",
    "type": "application/pdf",
    "length": 7951511,
    "originalFileName": "ESTANQUEIDADE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312529/download",
    "displayName": "Comprovação de cumprimento de exigências (novo texto 15-03-16)",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Solicitação",
    "id": "22224673",
    "type": "application/pdf",
    "length": 931032,
    "originalFileName": "SD_240715_141024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224673/download",
    "displayName": "Solicitação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovante de pagamento",
    "id": "22224679",
    "type": "application/pdf",
    "length": 445021,
    "originalFileName": "Boleto e Comprovante de pagamento.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224679/download",
    "displayName": "Comprovante de pagamento",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Procuração",
    "id": "22224685",
    "type": "application/pdf",
    "length": 170062,
    "originalFileName": "Procuração_240715_141053.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224685/download",
    "displayName": "Procuração",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Cópias simples do RG e do CPF ou da CNH",
    "id": "22312444",
    "type": "application/pdf",
    "length": 100634,
    "originalFileName": "CNPJ Auge2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312444/download",
    "displayName": "Cópias simples do RG e do CPF ou da CNH",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Ficha cadastral simplificada emitida pelo site da JUCESP",
    "id": "22312455",
    "type": "application/pdf",
    "length": 131867,
    "originalFileName": "ficha simplificada JUCESP.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312455/download",
    "displayName": "Ficha cadastral simplificada emitida pelo site da JUCESP",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documentação ME-EPP-MEI",
    "id": "22312486",
    "type": "application/pdf",
    "length": 644100,
    "originalFileName": "Declaração EPP.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312486/download",
    "displayName": "Documentação ME-EPP-MEI",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documento que comprove a propriedade do imóvel.",
    "id": "22224743",
    "type": "application/pdf",
    "length": 973344,
    "originalFileName": "Contrato social AUGE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224743/download",
    "displayName": "Documento que comprove a propriedade do imóvel.",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovação de área do terreno",
    "id": "22312479",
    "type": "application/pdf",
    "length": 1019405,
    "originalFileName": "Matricula AUGE Atualizada.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312479/download",
    "displayName": "Comprovação de área do terreno",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Mapa de acesso ao local.",
    "id": "22224702",
    "type": "application/pdf",
    "length": 229681,
    "originalFileName": "Mapa de Acesso.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224702/download",
    "displayName": "Mapa de acesso ao local.",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "MCE adicional de Renovação de Licença de Operação",
    "id": "22224712",
    "type": "application/pdf",
    "length": 293452,
    "originalFileName": "MCE Adicional_240715_141145.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224712/download",
    "displayName": "MCE adicional de Renovação de Licença de Operação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovação da solicitação",
    "id": "22312553",
    "type": "application/pdf",
    "length": 21203,
    "originalFileName": "Ibama Certificado Regularidade val 15.10.2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312553/download",
    "displayName": "Comprovação da solicitação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Certificado de Regularidade do Cadastro Técnico Federal",
    "id": "22224718",
    "type": "application/pdf",
    "length": 21203,
    "originalFileName": "Ibama Certificado Regularidade val 15.10.2024.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224718/download",
    "displayName": "Certificado de Regularidade do Cadastro Técnico Federal",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Documentação específica para licenciamento de Postos",
    "id": "22224719",
    "type": "application/pdf",
    "length": 7951511,
    "originalFileName": "ESTANQUEIDADE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224719/download",
    "displayName": "Documentação específica para licenciamento de Postos",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Manifestação do órgão responsável pelo sistema público de esgotos",
    "id": "22224722",
    "type": "application/pdf",
    "length": 295948,
    "originalFileName": "Conta de agua AUGE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224722/download",
    "displayName": "Manifestação do órgão responsável pelo sistema público de esgotos",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "MCE - Adicional de postos - renovação",
    "id": "22224729",
    "type": "application/pdf",
    "length": 412904,
    "originalFileName": "MCE Renovação_240715_141115.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22224729/download",
    "displayName": "MCE - Adicional de postos - renovação",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  },
  {
    "name": "Comprovação de cumprimento de exigências (novo texto 15-03-16)",
    "id": "22312529",
    "type": "application/pdf",
    "length": 7951511,
    "originalFileName": "ESTANQUEIDADE.pdf",
    "link": "https://e.ambiente.sp.gov.br/documents/v1/doc/22312529/download",
    "displayName": "Comprovação de cumprimento de exigências (novo texto 15-03-16)",
    "cdTipoDocDigital": null,
    "signed": false,
    "invalidName": false
  }
]